
name: docker-level1-build

on:
  push:
    branches: ["main"]

permissions: 
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login ghcr
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.repository_owner }}" \
            --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/$andrey666berkov/helloapi:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/helloapi:latest
