name: docker-level1-build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dokcer build
        run: |
          docker build -t helloapi:ci -f HelloApi/Dockerfile .
